---
title: "Class7"
author: "Amir Ferry"
date: "10/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Revisit our functions from last day

```{r}
source("http://tinyurl.com/rescale-R") # Barry's code 
```


## Adding an exclamation point flips it to "not ___"
if( !is.numeric(x) ) {
    stop("Input x should be numeric", call.=FALSE)
  }


We want to write a function, called both_na(), that counts how many positions in two input
vectors, x and y, both have a missing value
```{r}
# Create some data to have a simple test (answer should be 1)
x <- c(1,3,NA,5)
y <- c(2,NA,NA,7)

is.na(x)
```

```{r}
which(is.na(x)) # Found this on Stack Overflow, tell you position
```

```{r}
is.na(x) & is.na(y) 
```

```{r}
both_na <- function(x,y) {
sum(is.na(x) & is.na(y))
}

```

```{r}
both_na(x,y)
```

```{r}
x <- c(NA, NA, NA)
y1 <- c( 1, NA, NA)
y2 <- c( 1, NA, NA, NA)
y3 <- c(1, NA, NA, NA, NA, NA)

# Both of these will recycle the x vector
both_na(x,y2) 
both_na(x,y3)
```

```{r}
both_na2 <- function(x,y) {
  if(length(x) != length(y)) { # add STOP function to prevent it from running
  stop("ERROR, input vector should be same length", call. = FALSE) # Custom message + simplified to just show my message (.call function usually TRUE)
  }
sum(is.na(x) & is.na(y))
} 
```


## Goal is to calculate overall grade after dropping lowest score for each student
```{r}
# student 1
student1 <- c(100, 100, 100, 100, 100, 100, 100, 90)
# student 2
student2 <- c(100, NA, 90, 90, 90, 90, 97, 80)
# student 3
student3 <- c(100,NA,NA,NA,NA)
```

```{r}
student1[-which.min(student1)] # Adding a minus sign gives you everything except...
```

```{r}
mean(student2[-which.min(student2)], na.rm = TRUE)
```

```{r}
sum(student2[-which.min(student2)], na.rm = TRUE) / (length(student2) - 1)
```
```{r}
new_grade <- function(x) {
  sum(x[-which.min(x)], na.rm = TRUE) / (length(x) - 1)
}
```

```{r}
new_grade(student1)
new_grade(student2)
```


```






